<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Data\students.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>

    </None>
  </ItemGroup>




</Project>

